---
all:
  hosts:
  children:
    gateway:
      children:
        gateway_mysql:
          children:
            gateway_primary_db:
              hosts:
                master.10.demo:
                  src: rhel.94.demo
                  ansible_user: root
            gateway_failover_db:
              hosts:
                slave.10.demo:
                  src: slave.94.demo
                  ansible_user: root
        gateway_processing_node:
          hosts:
#            target-processing-gw.placeholder.com:
#              src: source-processing-gw.placeholder.com
        gateway_hsm:
          hosts:
        gateway_papim:
          chilren:
            gateway_papim_source:
              hosts:
            gateway_papim_install:
              hosts:
    hsm:
      children:
        hsm_luna7:
          hosts:
#            luna7.placeholder.com:
#              ansible_user: admin
#              ansible_connection: ssh
